spring:
  datasource:
    url: jdbc:mysql://db-connecta.cynh1jlres6n.us-east-2.rds.amazonaws.com:3306/paciente?serverTimezone=UTC
    username: paciente
    password: p4c13nt3
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect