spring:
  datasource:
    url: jdbc:mysql://db-connecta.cynh1jlres6n.us-east-2.rds.amazonaws.com:3306/planosaude?serverTimezone=UTC
    username: planosaude
    password: pl4n0s4ud3
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect