spring:
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate: INFO
