spring:
  datasource:
    url: jdbc:mysql://db-connecta-prd.cynh1jlres6n.us-east-2.rds.amazonaws.com:3306/connecta?serverTimezone=UTC
    username: connecta
    password: p4$$w0rdC0nn3ct4Pr0du(@0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  oauth2:
    resource:
      userInfoUri: https://service-authentication.connectacare.com.br/oauth2/userinfo
      tokenInfoUri: https://service-authentication.connectacare.com.br/oauth2/check_token