spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbconecta?serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  oauth2:
    resource:
      userInfoUri: http://service-authentication-env-stg.eba-fjvvj2se.us-east-2.elasticbeanstalk.com/oauth2/userinfo
      tokenInfoUri: http://service-authentication-env-stg.eba-fjvvj2se.us-east-2.elasticbeanstalk.com/oauth2/check_token
