spring:
  datasource:
    url: jdbc:mysql://db-connecta.cynh1jlres6n.us-east-2.rds.amazonaws.com:3306/connecta?serverTimezone=UTC
    username: connecta
    password: c0nn3ct4
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  oauth2:
    resource:
      userInfoUri: http://service-authentication-env-stg.eba-fjvvj2se.us-east-2.elasticbeanstalk.com/oauth2/userinfo
      tokenInfoUri: http://service-authentication-env-stg.eba-fjvvj2se.us-east-2.elasticbeanstalk.com/oauth2/check_token