spring:
  output:
    ansi:
      enabled: ALWAYS
  http:
    encoding:
      charset: UTF-8

management:
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate: INFO