spring:
  datasource:
    url: jdbc:mysql://db-connecta.cynh1jlres6n.us-east-2.rds.amazonaws.com:3306/homecare?serverTimezone=UTC
    username: homecare
    password: h0m3c4r3
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect